Expanded the APPRAISAL_INFO_EVENT decoding
tfarley/aclogview pull request #10
Opened 2017-04-29 03:32 UTC by OptimShi

I added a number of structures to the APPRAISAL_INFO_EVENT to effectively round out the parsing of it. There are a couple of bitfield entries that could probably still use to be expanded upon, though.

I also filled out the SpellID list. Not sure where the existing list came from, so I just took the actual spell names from the client and appended "_SpellID" to them to complete the list (renaming slightly in cases where there was a conflict).

I'm not sure if I followed the proper structure/format (if there is one?), so please feel free to critique me here and I'll be happy to make any required edits.

2017-04-30 07:47 UTC, tfarley commented
Oof, there are a ton of diff-but-not-changed lines in here. Is it a platform newline issue? Please try to get the unmodified lines out of the diff if possible - it's hard to tell what has actually changed here.

The spell list was from the 2013 client - so you're probably correct with these new ones, assuming that all of the SpellID indices line up with the indices in the client. In general, I try to follow a structure/naming scheme that matches exactly what the client officially calls things when available (i.e. from the PDB), so that it's easy to look stuff up when needed.

2017-05-05 21:51 UTC, OptimShi commented
Okay, I rebuilt this and that appears to have cleaned up the White Space issues. Not sure WHY it happened, but it's resolved. Thanks!

2017-05-10 04:52 UTC, tfarley requested changes
Whew, thanks for doing all of this, and for fixing the whitespace issue. Looking good - added a few comments.

2017-05-10 04:52 UTC, tfarley commented on aclogview/CM_Examine.cs
> +            rootNode.Nodes.Add("i_objid = " + Utility.FormatGuid(i_objid));
Thanks for adding the formatting :)

2017-05-10 04:52 UTC, tfarley commented on aclogview/CM_Examine.cs
> +            TreeNode armorProfileStatsNode = node.Nodes.Add("_armorProfile = ");
All of these tree nodes (including the spellbook above) should have "Stats" removed from their name, since they don't contain stats.

2017-05-10 04:52 UTC, tfarley commented on aclogview/CM_Examine.cs
> +            _spellsTable.contributeToTreeNode(spellStatsNode);
This should be wrapped in a bitfield check like the ones below

2017-05-10 04:52 UTC, tfarley commented on aclogview/CM_Examine.cs
> +            newObj._mod_vs_nether = binaryReader.ReadSingle();
electric and nether should be swapped

2017-05-10 04:52 UTC, tfarley commented on aclogview/CM_Examine.cs
> +            if ((_header & 0x8) != 0)
Please use CreatureAppraisalProfilePackHeader.Packed_Attributes constant here

2017-05-10 04:52 UTC, tfarley commented on aclogview/CM_Examine.cs
> +            if ((_header & 0x1) != 0)
Also Please use CreatureAppraisalProfilePackHeader.Packed_Enchantments here

2017-05-10 04:52 UTC, tfarley commented on aclogview/CM_Examine.cs
> +    public class WeaponAppraisalProfile
This one can just be "WeaponProfile" - no Appraisal needed.

2017-05-10 04:52 UTC, tfarley commented on aclogview/CM_Examine.cs
> +        public uint _ammoType;
This can be of type AMMO_TYPE

2017-05-10 04:52 UTC, tfarley commented on aclogview/CM_Examine.cs
> +                newObj.isLockpick = true;
These seem to match up with Enchantment_BFIndex - you should use i.e. Enchantment_BFIndex.BF_INSCRIBABLE instead of 0x1 etc.

2017-05-16 00:09 UTC, OptimShi commented
I've pushed your requested changes. Nice catch on the Nether/Electric order! I added in the listings for the three values that are just bitfields, just for completeness. I also found some logs for hooks (housing) and they appeared to parse as expected.

2017-05-17 05:13 UTC, tfarley requested changes
Nice, looks 99.9% good - just one little copy-paste error

2017-05-17 05:13 UTC, tfarley commented on aclogview/CM_Examine.cs
> +            if ((header & (uint)AppraisalProfilePackHeader.Packed_WeaponEnchant) != 0)
Should be Packed_ResistEnchant

2017-05-17 16:37 UTC, OptimShi commented on aclogview/CM_Examine.cs
> +            if ((header & (uint)AppraisalProfilePackHeader.Packed_WeaponEnchant) != 0)
Soooo close! Nice catch, thank you. I fixed it and pushed the changes.

2017-05-18 05:00 UTC, merged