Melee Combat Events
tfarley/aclogview pull request #13
Opened 2017-05-05 23:06 UTC by OptimShi

Added handlers for the following melee combat events:
ATTACKER_NOTIFICATION_EVENT
DEFENDER_NOTIFICATION_EVENT
EVASION_ATTACKER_NOTIFICATION_EVENT
EVASION_DEFENDER_NOTIFICATION_EVENT

2017-05-10 03:27 UTC, tfarley requested changes
Thanks for the PR. Just left a few comments for small fixes.

2017-05-10 03:27 UTC, tfarley commented on aclogview/CM_Combat.cs
> +            newObj.critical = binaryReader.ReadBoolean();
From what I can see, it looks like critical is actually a full int, not just a single byte.

2017-05-10 03:27 UTC, tfarley commented on aclogview/CM_Combat.cs
> +            newObj.critical = binaryReader.ReadBoolean();
Same, full int instead of bool for critical.

2017-05-10 03:27 UTC, tfarley commented on aclogview/CM_Combat.cs
> +        public PStringChar defenders_name;
This should be attackers_name

2017-05-10 03:27 UTC, tfarley commented on aclogview/CM_Combat.cs
> +            rootNode.Nodes.Add("defenders_name = " + defenders_name);
attackers_name

2017-05-10 03:27 UTC, tfarley commented on aclogview/CM_Combat.cs
> +        public PStringChar attacker;
Please make this defenders_name, just to be consistent

2017-05-10 03:27 UTC, tfarley commented on aclogview/CM_Combat.cs
> +            rootNode.Nodes.Add("attacker = " + attacker);
defenders_name

2017-05-10 03:27 UTC, tfarley commented on aclogview/CM_Combat.cs
> +        public PStringChar attacker;
Please make this attackers_name, just to be consistent

2017-05-10 03:27 UTC, tfarley commented on aclogview/CM_Combat.cs
> +            rootNode.Nodes.Add("defender = " + attacker);
attackers_name

2017-05-10 03:27 UTC, tfarley commented on aclogview/Enums/Combat.cs
> +    UNDEFINED,
These actually all need to shift by -1, so UNDEFINED = -1, HEAD = 0, CHEST = 1, etc. I would suggest just getting rid of the UNDEFINED entry.

2017-05-10 03:27 UTC, tfarley commented on aclogview/Enums/Combat.cs
> +    SKIP_2, // Skip 15
After the above change, these two comments then become Skip 11 and Skip 14

2017-05-12 16:38 UTC, OptimShi commented
Thanks for taking the time to look at this and catch my mistakes! I've adjusted with your feedback and also added the enum for the "attack_conditions" bitfield (not currently reading them, but they are least there for reference for the time being)

2017-05-17 04:58 UTC, merged