Emote Decoding
tfarley/aclogview pull request #17
Opened 2017-05-13 13:14 UTC by fantoms

* Added Emote
* Added HearEmote 
* Added SoulEmote
* Added HearSoulEmote

2017-05-14 02:54 UTC, fantoms commented
* Added TransientString

2017-05-14 14:42 UTC, fantoms commented
* Added PopUpString: // 0x0004

2017-05-17 05:52 UTC, tfarley requested changes
Looking good. Just a couple ordering things.

2017-05-17 05:52 UTC, tfarley commented on aclogview/CM_Communication.cs
> +        public uint SenderID;
Please reorder the declarations and order of nodes in the tree view to match the read order

2017-05-17 05:52 UTC, tfarley commented on aclogview/CM_Communication.cs
> +        public uint SenderID;
Same here - Please reorder the declarations and order of nodes in the tree view to match the read order

2017-05-17 20:29 UTC, fantoms commented
The 2 changes request have been corrected. Thank you for looking over my contributions, once again!

2017-05-18 00:49 UTC, fantoms commented
These changes should be ready to merge if you're comfortable with them.

2017-05-18 03:41 UTC, merged