Added lifestone Materialize, Movement and Position Update Event
tfarley/aclogview pull request #7
Opened 2017-04-14 22:40 UTC by fantoms

Please check to verify that I made the correct assumptions on this one. Documentation used: 

http://skunkworks.sourceforge.net/protocol/Protocol.php?stylesheet=Classic.css&frame=frameMsg&type=F619

http://www.virindi.net/junk/messages_annotated_final.xml :

`<message type="F619" name="Lifestone Materialize" text="Sent when a character rematerializes at the lifestone after death." lastUpdate="20050918" lastUpdater="kgober"><field type="ObjectID" name="object" text="ObjectID of the character doing the animation"/><field type="Position" name="position"/><field type="DWORD" name="unknown2" text="Unknown"/><field type="DWORD" name="unknown3" text="Unknown"/><field type="DWORD" name="unknown4" text="Unknown"/><field type="DWORD" name="unknown5" text="Unknown"/></message>`

2017-04-15 04:43 UTC, tfarley requested changes

2017-04-15 04:43 UTC, tfarley commented on aclogview/CM_Movement.cs
> +            newObj.Position = Position.read(binaryReader);
Looks like there are 4 unknown bytes between the object id and the position. It also looks like there are at least 24 bytes following the position. Suggest adding an unknown int between id and position as well as adding two more unknown ints to the end to fully read the packet.

2017-04-15 04:43 UTC, tfarley commented on aclogview/CM_Movement.cs
> +            newObj.ObjectId = binaryReader.ReadInt32();
Id should be unsigned int.

2017-04-16 19:07 UTC, fantoms commented
Thank you!

I've updated this branch with your suggestions; please review and let me know what you think. I'm seeing the results of "WARNING: Prev fragment not fully read!".

2017-04-17 00:08 UTC, tfarley requested changes

2017-04-17 00:08 UTC, tfarley commented on aclogview/CM_Movement.cs
> +            newObj.unknown3 = binaryReader.ReadInt32();
Thanks for the changes. Was intending for two _more_ ints after position though - id, unk1, pos, unk2, unk3, unk4, unk5, unk6, unk7. Naturally we have no idea if those are actually ints, but at least the whole fragment gets read that way and you won't get that warning.

2017-04-17 02:23 UTC, fantoms commented on aclogview/CM_Movement.cs
> +            newObj.unknown3 = binaryReader.ReadInt32();
Perfect, I was also getting quite confused as to how that would work. Thank you for the further clarification, it should now be set!

2017-04-18 02:06 UTC, fantoms commented
Should be ready to review, the warning has now disappeared.

2017-04-18 03:10 UTC, tfarley commented
Great, thanks. Sorry for the confusion. :)

2017-04-18 03:10 UTC, merged